QUESTIONS = [
    {
        "q_es": "¿Cuántos satoshis tiene 1 BTC?",
        "q_en": "How many satoshis are in 1 BTC?",
        "options_es": ["1,000,000", "10,000,000", "100,000,000", "1,000,000,000"],
        "options_en": ["1,000,000", "10,000,000", "100,000,000", "1,000,000,000"],
        "correct": 2,
        "exp_es": "1 BTC es igual a 100,000,000 sats, es decir cien millones.",
        "exp_en": "1 BTC equals 100,000,000 sats, that is one hundred million.",
    },
    {
        "q_es": "¿Cuál es el suministro maximo total de Bitcoin?",
        "q_en": "What is the maximum total supply of Bitcoin?",
        "options_es": ["21 millones", "100 millones", "210 millones", "Ilimitado"],
        "options_en": ["21 million", "100 million", "210 million", "Unlimited"],
        "correct": 0,
        "exp_es": "Nunca existiran mas de 21 millones de bitcoins.",
        "exp_en": "There will never be more than 21 million bitcoins.",
    },
    {
        "q_es": "¿Cada cuantos bloques ocurre el halving de Bitcoin?",
        "q_en": "Every how many blocks does the Bitcoin halving occur?",
        "options_es": ["21,000 bloques", "100,000 bloques", "210,000 bloques", "500,000 bloques"],
        "options_en": ["21,000 blocks", "100,000 blocks", "210,000 blocks", "500,000 blocks"],
        "correct": 2,
        "exp_es": "El halving ocurre cada 210,000 bloques, aproximadamente cada 4 anos.",
        "exp_en": "The halving happens every 210,000 blocks, roughly every 4 years.",
    },
    {
        "q_es": "¿Quien creo Bitcoin?",
        "q_en": "Who created Bitcoin?",
        "options_es": ["Vitalik Buterin", "Satoshi Nakamoto", "Elon Musk", "Hal Finney"],
        "options_en": ["Vitalik Buterin", "Satoshi Nakamoto", "Elon Musk", "Hal Finney"],
        "correct": 1,
        "exp_es": "Bitcoin fue creado por el seudonimo Satoshi Nakamoto.",
        "exp_en": "Bitcoin was created by the pseudonym Satoshi Nakamoto.",
    },
    {
        "q_es": "¿En que ano se mino el bloque genesis de Bitcoin?",
        "q_en": "In what year was the Bitcoin genesis block mined?",
        "options_es": ["2007", "2008", "2009", "2011"],
        "options_en": ["2007", "2008", "2009", "2011"],
        "correct": 2,
        "exp_es": "El bloque genesis, el primer bloque, se mino en enero de 2009.",
        "exp_en": "The genesis block, the first block, was mined in January 2009.",
    },
    {
        "q_es": "¿Que debes hacer con tu frase semilla de 12 o 24 palabras?",
        "q_en": "What should you do with your 12 or 24 word seed phrase?",
        "options_es": ["Compartirla con soporte", "Guardarla en secreto y sin conexion", "Publicarla online", "Enviarla por chat"],
        "options_en": ["Share it with support", "Keep it secret and offline", "Post it online", "Send it by chat"],
        "correct": 1,
        "exp_es": "La frase semilla controla tus fondos, asi que guardala en secreto y sin conexion.",
        "exp_en": "The seed phrase controls your funds, so keep it secret and offline.",
    },
    {
        "q_es": "¿Que significa la frase not your keys, not your coins?",
        "q_en": "What does the phrase not your keys, not your coins mean?",
        "options_es": ["Si no controlas las claves, no controlas tus bitcoins", "Las claves son gratis", "Solo importan las monedas", "Pierdes monedas al usar claves"],
        "options_en": ["If you do not control the keys, you do not control your bitcoins", "Keys are free", "Only coins matter", "You lose coins by using keys"],
        "correct": 0,
        "exp_es": "Si un tercero tiene tus claves privadas, realmente controla tus bitcoins.",
        "exp_en": "If a third party holds your private keys, they really control your bitcoins.",
    },
    {
        "q_es": "¿Cual clave puedes compartir para recibir bitcoins?",
        "q_en": "Which key can you share to receive bitcoins?",
        "options_es": ["La clave privada", "La frase semilla", "La clave publica", "El PIN del wallet"],
        "options_en": ["The private key", "The seed phrase", "The public key", "The wallet PIN"],
        "correct": 2,
        "exp_es": "La clave publica, o direccion, es la que compartes para recibir fondos.",
        "exp_en": "The public key, or address, is the one you share to receive funds.",
    },
    {
        "q_es": "¿Que es la blockchain de Bitcoin?",
        "q_en": "What is the Bitcoin blockchain?",
        "options_es": ["Una empresa privada", "Un libro de cuentas publico de bloques enlazados", "Un banco central", "Una app de mensajeria"],
        "options_en": ["A private company", "A public ledger of linked blocks", "A central bank", "A messaging app"],
        "correct": 1,
        "exp_es": "La blockchain es un libro de cuentas publico formado por bloques enlazados.",
        "exp_en": "The blockchain is a public ledger made of linked blocks.",
    },
    {
        "q_es": "¿Que mecanismo usa Bitcoin para asegurar la red mediante mineria?",
        "q_en": "What mechanism does Bitcoin use to secure the network through mining?",
        "options_es": ["Prueba de Participacion", "Prueba de Autoridad", "Prueba de Trabajo", "Prueba de Espacio"],
        "options_en": ["Proof of Stake", "Proof of Authority", "Proof of Work", "Proof of Space"],
        "correct": 2,
        "exp_es": "Bitcoin usa Prueba de Trabajo, donde los mineros gastan energia para validar bloques.",
        "exp_en": "Bitcoin uses Proof of Work, where miners spend energy to validate blocks.",
    },
    {
        "q_es": "¿Para que sirve la Lightning Network?",
        "q_en": "What is the Lightning Network used for?",
        "options_es": ["Pagos rapidos y baratos fuera de la cadena", "Minar mas rapido", "Crear nuevas monedas", "Borrar transacciones"],
        "options_en": ["Fast and cheap payments off chain", "Mine faster", "Create new coins", "Delete transactions"],
        "correct": 0,
        "exp_es": "Lightning permite pagos rapidos y baratos en una segunda capa sobre Bitcoin.",
        "exp_en": "Lightning enables fast and cheap payments on a second layer over Bitcoin.",
    },
    {
        "q_es": "¿Que es el mempool en Bitcoin?",
        "q_en": "What is the mempool in Bitcoin?",
        "options_es": ["Un tipo de wallet", "La sala de espera de transacciones sin confirmar", "Una bolsa de mineria", "Un exchange"],
        "options_en": ["A type of wallet", "The waiting room of unconfirmed transactions", "A mining pool", "An exchange"],
        "correct": 1,
        "exp_es": "El mempool es donde esperan las transacciones antes de entrar en un bloque.",
        "exp_en": "The mempool is where transactions wait before being included in a block.",
    },
    {
        "q_es": "¿Que hace un nodo completo de Bitcoin?",
        "q_en": "What does a Bitcoin full node do?",
        "options_es": ["Solo mina bloques", "Verifica y aplica las reglas de la red", "Vende bitcoins", "Crea claves privadas para otros"],
        "options_en": ["Only mines blocks", "Verifies and enforces the network rules", "Sells bitcoins", "Creates private keys for others"],
        "correct": 1,
        "exp_es": "Un nodo verifica las transacciones y aplica las reglas de la red por si mismo.",
        "exp_en": "A node verifies transactions and enforces the network rules on its own.",
    },
    {
        "q_es": "¿Que define el estandar BIP39?",
        "q_en": "What does the BIP39 standard define?",
        "options_es": ["El tamano del bloque", "La frase semilla de palabras mnemotecnicas", "El precio del bitcoin", "La velocidad de la red"],
        "options_en": ["The block size", "The mnemonic word seed phrase", "The price of bitcoin", "The network speed"],
        "correct": 1,
        "exp_es": "BIP39 define las palabras mnemotecnicas usadas en la frase semilla.",
        "exp_en": "BIP39 defines the mnemonic words used in the seed phrase.",
    },
    {
        "q_es": "¿Cual es la diferencia principal entre un cold wallet y un hot wallet?",
        "q_en": "What is the main difference between a cold wallet and a hot wallet?",
        "options_es": ["El color del dispositivo", "El cold wallet esta sin conexion y el hot wallet conectado", "El cold wallet es mas caro siempre", "No hay diferencia"],
        "options_en": ["The color of the device", "A cold wallet is offline and a hot wallet is online", "A cold wallet is always more expensive", "There is no difference"],
        "correct": 1,
        "exp_es": "Un cold wallet guarda las claves sin conexion y un hot wallet permanece conectado.",
        "exp_en": "A cold wallet keeps keys offline while a hot wallet stays connected to the internet.",
    },
    {
        "q_es": "¿Que significa DCA en el contexto de Bitcoin?",
        "q_en": "What does DCA mean in the Bitcoin context?",
        "options_es": ["Promediar el costo comprando montos fijos con regularidad", "Vender todo de golpe", "Minar a diario", "Cambiar de wallet"],
        "options_en": ["Dollar cost averaging by buying fixed amounts regularly", "Selling everything at once", "Mining daily", "Switching wallets"],
        "correct": 0,
        "exp_es": "DCA es comprar montos fijos de forma regular para promediar el precio.",
        "exp_en": "DCA is buying fixed amounts on a regular schedule to average out the price.",
    },
    {
        "q_es": "¿Que significa HODL en la comunidad Bitcoin?",
        "q_en": "What does HODL mean in the Bitcoin community?",
        "options_es": ["Vender en panico", "Mantener a largo plazo sin vender", "Un tipo de mineria", "Una comision de red"],
        "options_en": ["Selling in panic", "Holding long term without selling", "A type of mining", "A network fee"],
        "correct": 1,
        "exp_es": "HODL significa mantener tus bitcoins a largo plazo sin vender por panico.",
        "exp_en": "HODL means holding your bitcoins long term without panic selling.",
    },
    {
        "q_es": "¿Cada cuanto tiempo se mina un nuevo bloque de Bitcoin en promedio?",
        "q_en": "On average, how often is a new Bitcoin block mined?",
        "options_es": ["Cada 1 minuto", "Cada 10 minutos", "Cada 1 hora", "Cada 24 horas"],
        "options_en": ["Every 1 minute", "Every 10 minutes", "Every 1 hour", "Every 24 hours"],
        "correct": 1,
        "exp_es": "En promedio se mina un bloque nuevo cada 10 minutos aproximadamente.",
        "exp_en": "On average a new block is mined roughly every 10 minutes.",
    },
]
